old_layers = [
    "ALTRI IMPIANTI",
    "ASSI",
    "CONTORNI",
    "CONTORNI 2",
    "CONTORNI 3",
    "ESISTENTE",
    "LANG-FR",
    "LANG-IN-R1",
    "LANG-IN-R2",
    "LANG-IT",
    "LANG-SP",
    "NASCOSTE",
    "NOTE",
    "QUOTE",
    "REDECAM_Blocco_Bulloneria",
    "REDECAM_Blocco_Distinta",
    "REDECAM_Bocco_Guarnizioni",
    "REDECAM_Squadratura_Cartiglio",
    "REDECAM_FASTENER",
    "REDECAM_FITTING+OTHERS",
    "REDECAM_GASKET",
    "REDECAM_RAW+INSULATION",
    "REDECAM_STEELWORK",
    "REDECAM_TITLE-BLOCK",
    "SOTTILI",
    "TESTI",
    "TRATTEGGI",
]